language: php

php:
    - 5.5
    - 5.6
    - 7.0

install:
    - composer install

script:
    - ./bin/test
    - ./vendor/bin/phpspec r -c tests/phpspec/phpspec-codecoverage.yml

after_script:
    - php vendor/bin/coveralls -v
