language: php

php:
    - 5.5
    - 5.6
    - 7.0

install:
    - composer install

script:
    - ./bin/test

after_script:
    - ./vendor/bin/phpspec r -c tests/phpspec/phpspec-codecoverage.yml
    - php ./vendor/bin/coveralls.php -v
